import type { Metadata } from "next";
import "./globals.css";
import { ServerRoot } from "./_root/ServerRoot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ServerRoot>{children}</ServerRoot>;
}
